const $=id=>document.getElementById(id);
const Forge=window.LadyDelilahForge;
const EFFECTS={damage:'Damage',armor:'Armor',heal:'Heal',status:'Status',draw:'Draw',energy:'Energy',conditionalDamage:'Conditional damage'};
const STATUSES=['Bleeding','Flanked','Terrified'];
const ICONS={Attack:'⚔',Guard:'◆',Trap:'🔥',Precision:'◉',Survival:'❖',Companion:'🐺'};

function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fillOptions(select,items,includeNone=false){select.innerHTML=(includeNone?'<option value="">None</option>':'')+Object.entries(items).map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}
function statusOptions(select){select.innerHTML=STATUSES.map(x=>`<option>${x}</option>`).join('')}
fillOptions($('primaryType'),EFFECTS);fillOptions($('secondaryType'),EFFECTS,true);statusOptions($('primaryStatus'));statusOptions($('secondaryStatus'));

function effectFrom(prefix){const type=$(`${prefix}Type`).value;if(!type)return null;const amount=Math.max(0,Number($(`${prefix}Amount`).value)||0);const effect={type,amount,target:['armor','heal','draw','energy'].includes(type)?'player':'enemy'};if(type==='status')effect.status=$(`${prefix}Status`).value;if(type==='conditionalDamage'){effect.status=$(`${prefix}Status`).value;effect.condition=`target-${effect.status.toLowerCase()}`}return effect}
function rulesFor(effects){return effects.map(e=>{if(e.type==='damage')return `Deal ${e.amount} damage.`;if(e.type==='conditionalDamage')return `Deal ${e.amount} damage if the enemy is ${e.status}.`;if(e.type==='armor')return `Gain ${e.amount} Armor.`;if(e.type==='heal')return `Heal ${e.amount}.`;if(e.type==='status')return `Apply ${e.amount} ${e.status}.`;if(e.type==='draw')return `Draw ${e.amount} card${e.amount===1?'':'s'}.`;if(e.type==='energy')return `Gain ${e.amount} Energy.`;return ''}).join(' ')}
function draft(){const effects=[effectFrom('primary'),effectFrom('secondary')].filter(e=>e&&e.amount>0);return {name:$('cardName').value.trim(),cost:Number($('cardCost').value),type:$('cardType').value,rarity:'Forged',icon:ICONS[$('cardType').value]||'✦',rulesText:rulesFor(effects),flavorText:$('flavorText').value.trim(),keywords:[...new Set(effects.map(e=>e.status||EFFECTS[e.type]).filter(Boolean))],exhaust:$('exhaust').checked,effects}}
function heat(evaluation){if(evaluation.verdict==='invalid')return ['Cold',8];if(evaluation.verdict==='under-forged')return ['Warm',38];if(evaluation.verdict==='balanced')return ['Hot',68];if(evaluation.verdict==='tempered')return ['White Hot',90];return ['Breaking',100]}
function refreshTokens(){const b=Forge.tokenBalance();$('tokenCount').textContent=b.total;$('tokenDetail').textContent=`${b.permanent} permanent · ${b.run} from this run`}
function render(){const card=draft(),evaluation=Forge.evaluateCard(card),[word,width]=heat(evaluation);$('previewName').textContent=card.name||'Untitled Card';$('previewCost').textContent=card.cost;$('previewIcon').textContent=card.icon;$('previewType').textContent=`${card.type.toUpperCase()} · FORGED`;$('previewRules').textContent=card.rulesText||'The steel is waiting.';$('previewFlavor').textContent=card.flavorText;$('verdictText').textContent=evaluation.jonas;$('jonasLine').textContent=`“${evaluation.jonas}”`;$('heatWord').textContent=word;$('heatBar').style.width=`${width}%`;const balance=Forge.tokenBalance();$('strikeBtn').disabled=!evaluation.valid||balance.total<1;$('forgeError').textContent=evaluation.errors.join(' ')||(balance.total<1?'Earn a Forge Token before striking the anvil.':'')}

function renderVault(){let cards=Forge.listForgedCards();const q=$('vaultSearch').value.trim().toLowerCase();if(q)cards=cards.filter(c=>`${c.name} ${c.forge?.forgedReason||''}`.toLowerCase().includes(q));const sort=$('vaultSort').value;if(sort==='oldest')cards.sort((a,b)=>new Date(a.forge.forgedDate)-new Date(b.forge.forgedDate));else if(sort==='name')cards.sort((a,b)=>a.name.localeCompare(b.name));else cards.sort((a,b)=>new Date(b.forge.forgedDate)-new Date(a.forge.forgedDate));$('vaultGrid').innerHTML=cards.length?cards.map(c=>`<article class="vault-card"><h3>${escapeHtml(c.name)}</h3><b>${c.cost} Energy · ${escapeHtml(c.type)}</b><p>${escapeHtml(c.rulesText)}</p><small>Forged by ${escapeHtml(c.forge?.forgedBy||'Player')}<br>${escapeHtml(c.forge?.forgedReason||'Earned in the hunt')}<br>${new Date(c.forge?.forgedDate).toLocaleDateString()}</small></article>`).join(''):'<p class="muted">The Vault is empty. Its shelves are patient.</p>'}
function openVault(){renderVault();$('vaultDialog').showModal()}

const renderForgeLegacy=render;render=function(){renderForgeLegacy();const card=draft();window.SystemaCardCatalog={[card.name]:card};SystemaCardRenderer.renderInto($('cardPreview'),card,{mode:'expanded'})};
renderVault=function(){let cards=Forge.listForgedCards();const q=$('vaultSearch').value.trim().toLowerCase();if(q)cards=cards.filter(c=>`${c.name} ${c.forge?.forgedReason||''}`.toLowerCase().includes(q));const sort=$('vaultSort').value;if(sort==='oldest')cards.sort((a,b)=>new Date(a.forge.forgedDate)-new Date(b.forge.forgedDate));else if(sort==='name')cards.sort((a,b)=>a.name.localeCompare(b.name));else cards.sort((a,b)=>new Date(b.forge.forgedDate)-new Date(a.forge.forgedDate));window.SystemaCardCatalog=Object.fromEntries(cards.map(c=>[c.id,c]));$('vaultGrid').innerHTML=cards.length?cards.map(c=>`<article class="vault-card" data-card-id="${escapeHtml(c.id)}">${SystemaCardRenderer.html(c,{mode:'collection'})}<small>Forged by ${escapeHtml(c.forge?.forgedBy||'Player')}<br>${escapeHtml(c.forge?.forgedReason||'Earned in the hunt')}<br>${new Date(c.forge?.forgedDate).toLocaleDateString()}</small></article>`).join(''):'<p class="muted">The Vault is empty. Its shelves are patient.</p>'};
document.querySelectorAll('input,select,textarea').forEach(el=>el.addEventListener('input',render));
$('forgeForm').addEventListener('submit',e=>{e.preventDefault();const card=draft();const result=Forge.forgeCard(card,{forgedBy:localStorage.getItem('lady-delilah-player-name')||'Player',forgedReason:'Forged in Jonas’ workshop',artworkPool:card.type});if(!result.ok){$('forgeError').textContent=result.error||result.evaluation.errors.join(' ');render();return}document.body.classList.add('struck');setTimeout(()=>document.body.classList.remove('struck'),800);$('forgedTitle').textContent=result.card.name;$('forgedMeta').textContent=`${result.card.rulesText} The card is now permanent.`;$('successDialog').showModal();refreshTokens();render();window.dispatchEvent(new CustomEvent('forge:anvil-struck',{detail:result.card}))});
$('vaultBtn').addEventListener('click',openVault);$('viewVaultBtn').addEventListener('click',()=>{$('successDialog').close();openVault()});$('closeVaultBtn').addEventListener('click',()=>$('vaultDialog').close());$('vaultSearch').addEventListener('input',renderVault);$('vaultSort').addEventListener('change',renderVault);
window.addEventListener('forge:token-awarded',()=>{refreshTokens();render()});
refreshTokens();render();
