const $=id=>document.getElementById(id);
const fields=['cardId','title','cost','type','rarity','archetype','setName','rules','flavor','keywords'];
const defaults={cardId:'done-here',title:'C’mon, Lady… We’re Done Here',cost:3,type:'Attack',rarity:'Legendary',archetype:'Synchronized',setName:'Base Set',rules:'Deal 18 damage. Execute if the target is Bleeding, Flanked, or Terrified below 40% Health.',flavor:'“Lady doesn’t ask twice. Neither do I.” — Delilah',keywords:'Bleeding, Execute, Flanked'};
let artData='';
function data(){return {schemaVersion:1,id:$('cardId').value.trim(),name:$('title').value.trim(),cost:Number($('cost').value),type:$('type').value,rarity:$('rarity').value,archetype:$('archetype').value.trim(),set:$('setName').value.trim(),rulesText:$('rules').value.trim(),flavorText:$('flavor').value.trim(),keywords:$('keywords').value.split(',').map(x=>x.trim()).filter(Boolean),artwork:artData?'embedded-preview':'',game:{target:'enemy',exhaust:false,upgradeable:true}}}
function render(){const d=data();$('pCost').textContent=d.cost;$('pTitle').textContent=d.name;$('pFlavorTop').textContent=d.flavorText.split('—')[0].trim();$('pType').textContent=d.type.toUpperCase();$('pArchetype').textContent=d.archetype.toUpperCase();$('pRarity').textContent=d.rarity.toUpperCase();$('pRules').textContent=d.rulesText;$('pSet').textContent=d.set.toUpperCase();$('pId').textContent=d.id.toUpperCase();$('gameCard').className='game-card rarity-'+d.rarity.toLowerCase();$('keywordBadges').innerHTML=d.keywords.map(k=>`<span class="keyword">${escapeHtml(k)}</span>`).join('');$('jsonPreview').textContent=JSON.stringify(d,null,2);const valid=d.id&&d.name&&Number.isFinite(d.cost)&&d.rulesText;$('validationBadge').textContent=valid?'Ready':'Needs attention';$('validationBadge').style.background=valid?'#173226':'#432022'}
function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
fields.forEach(id=>$(id).addEventListener('input',render));
$('artInput').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{artData=r.result;$('artFrame').style.backgroundImage=`url(${artData})`;$('artFrame').querySelector('.art-placeholder').style.display='none';render()};r.readAsDataURL(f)});
$('downloadJson').addEventListener('click',()=>{const d=data();const blob=new Blob([JSON.stringify(d,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(d.id||'game-card')+'.json';a.click();URL.revokeObjectURL(a.href)});
$('copyJson').addEventListener('click',async()=>{await navigator.clipboard.writeText(JSON.stringify(data(),null,2));$('copyJson').textContent='Copied';setTimeout(()=>$('copyJson').textContent='Copy JSON',1200)});
$('resetCard').addEventListener('click',()=>{Object.entries(defaults).forEach(([k,v])=>$(k).value=v);artData='';$('artFrame').style.backgroundImage='';$('artFrame').querySelector('.art-placeholder').style.display='grid';render()});
render();
