const $=id=>document.getElementById(id);
const STORAGE_KEY='systema-obscura-card-studio-v3';
const fields=['cardId','title','cost','type','rarity','archetype','setName','cardNumber','target','power','rules','flavor','keywords','developerNotes','artPrompt','exhaust','upgradeable'];
const sectionHelp={identity:['Identity','Name the card, place it in a set, and assign its visual tier.'],gameplay:['Gameplay','Define how the card behaves during play.'],effects:['Effect Builder','Build structured effects without editing JSON by hand.'],lore:['Lore & Notes','Keep player-facing flavor separate from private design intent.'],library:['Card Library','Save, search, and reopen cards in this browser.'],export:['Export','Review and export game-ready card data.']};
const defaults={cardId:'done-here',title:'C’mon, Lady… We’re Done Here',cost:3,type:'Attack',rarity:'Legendary',archetype:'Synchronized',setName:'Base Set',cardNumber:'LD-001',target:'enemy',power:18,rules:'Deal 18 damage. Execute if the target is Bleeding, Flanked, or Terrified below 40% Health.',flavor:'“Lady doesn’t ask twice. Neither do I.” — Delilah',keywords:'Bleeding, Execute, Flanked',developerNotes:'Signature finisher. Teaches Execute and synchronized play. Keep expensive enough that it feels earned.',artPrompt:'Delilah and Lady ending a moonlit hunt, forged dark-fantasy card art, cinematic, no text.',exhaust:false,upgradeable:true};
let artData='';let effects=[{action:'damage',amount:18,status:'',condition:'target-below-40'}];let currentSavedId='';
function library(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]')}catch{return[]}}
function setLibrary(cards){localStorage.setItem(STORAGE_KEY,JSON.stringify(cards))}
function keywords(){return $('keywords').value.split(',').map(x=>x.trim()).filter(Boolean)}
function data(){return {schemaVersion:2,id:$('cardId').value.trim(),name:$('title').value.trim(),cardNumber:$('cardNumber').value.trim(),cost:Number($('cost').value),type:$('type').value,rarity:$('rarity').value,archetype:$('archetype').value.trim(),set:$('setName').value.trim(),rulesText:$('rules').value.trim(),flavorText:$('flavor').value.trim(),keywords:keywords(),artwork:artData?'embedded-preview':'',artworkPrompt:$('artPrompt').value.trim(),developerNotes:$('developerNotes').value.trim(),game:{target:$('target').value,power:Number($('power').value),exhaust:$('exhaust').checked,upgradeable:$('upgradeable').checked,effects:[...effects]}}}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function validate(d){const checks=[!!d.id,!!d.name,!!d.cardNumber,Number.isFinite(d.cost),d.cost>=0,!!d.rulesText,!!d.set,!!d.type];const score=Math.round(checks.filter(Boolean).length/checks.length*100);return {score,ready:score===100}}
function render(){const d=data();$('pCost').textContent=d.cost;$('pTitle').textContent=d.name||'Untitled Card';$('pFlavorTop').textContent=(d.flavorText.split('—')[0]||'').trim();$('pType').textContent=d.type.toUpperCase();$('pArchetype').textContent=(d.archetype||'UNASSIGNED').toUpperCase();$('pRarity').textContent=d.rarity.toUpperCase();$('pRules').textContent=d.rulesText||'Add rules text.';$('pSet').textContent=(d.set||'NO SET').toUpperCase();$('pNumber').textContent=(d.cardNumber||d.id||'UNNUMBERED').toUpperCase();$('gameCard').className='game-card rarity-'+d.rarity.toLowerCase();$('keywordBadges').innerHTML=d.keywords.map(k=>`<span class="keyword">${escapeHtml(k)}</span>`).join('');$('jsonPreview').textContent=JSON.stringify(d,null,2);const v=validate(d);$('healthScore').textContent=v.score+'%';$('validationBadge').textContent=v.ready?'Ready':'Needs attention';$('validationBadge').style.background=v.ready?'#173226':'#432022';$('previewStatus').textContent=currentSavedId===d.id?'Saved locally':'Unsaved changes'}
function showSection(name){document.querySelectorAll('.studio-section').forEach(x=>x.classList.toggle('is-active',x.dataset.panel===name));document.querySelectorAll('.section-link').forEach(x=>x.classList.toggle('is-active',x.dataset.section===name));$('workspaceTitle').textContent=sectionHelp[name][0];$('workspaceHelp').textContent=sectionHelp[name][1];if(name==='library')renderLibrary()}
function effectText(e){const names={damage:'Deal Damage',block:'Gain Block',status:'Apply Status',draw:'Draw Cards',energy:'Gain Energy'};const conditions={none:'No condition','target-below-40':'Target below 40% Health','target-bleeding':'Target is Bleeding','target-flanked':'Target is Flanked','bond-ready':'Bond is Ready'};return `${names[e.action]} ${e.amount}${e.status?` • ${e.status}`:''}`+` • ${conditions[e.condition]}`}
function renderEffects(){$('effectList').innerHTML=effects.length?effects.map((e,i)=>`<div class="effect-item"><div><strong>${escapeHtml(effectText(e))}</strong><small>Structured effect ${i+1}</small></div><button data-remove-effect="${i}">Remove</button></div>`).join(''):'<div class="effect-item"><div><strong>No structured effects yet</strong><small>Add one above. Rules text can still be written normally.</small></div></div>';render()}
function saveCard(){const d=data();if(!d.id){alert('Give the card an ID before saving.');return}const cards=library();const index=cards.findIndex(c=>c.id===d.id);const record={...d,artData,updatedAt:new Date().toISOString()};if(index>=0)cards[index]=record;else cards.push(record);setLibrary(cards);currentSavedId=d.id;$('previewStatus').textContent='Saved locally';renderLibrary()}
function loadCard(card){fields.forEach(id=>{if(id==='exhaust'||id==='upgradeable')$(id).checked=!!card.game?.[id];else if(id==='power')$(id).value=card.game?.power??0;else if(id==='target')$(id).value=card.game?.target||'enemy';else if(id==='keywords')$(id).value=(card.keywords||[]).join(', ');else if(id==='cardId')$(id).value=card.id||'';else if(id==='title')$(id).value=card.name||'';else if(id==='setName')$(id).value=card.set||'';else if(id==='rules')$(id).value=card.rulesText||'';else if(id==='flavor')$(id).value=card.flavorText||'';else if(id==='artPrompt')$(id).value=card.artworkPrompt||'';else if(id==='developerNotes')$(id).value=card.developerNotes||'';else if(card[id]!==undefined)$(id).value=card[id]});effects=[...(card.game?.effects||[])];artData=card.artData||'';$('artFrame').style.backgroundImage=artData?`url(${artData})`:'';$('artFrame').querySelector('.art-placeholder').style.display=artData?'none':'grid';currentSavedId=card.id;renderEffects();showSection('identity')}
function renderLibrary(){const q=$('librarySearch').value.toLowerCase();const r=$('libraryRarity').value;const cards=library().filter(c=>(!q||`${c.name} ${c.id} ${c.set}`.toLowerCase().includes(q))&&(!r||c.rarity===r));$('cardLibrary').innerHTML=cards.length?cards.map(c=>`<article class="library-card" data-card-id="${escapeHtml(c.id)}"><h3>${escapeHtml(c.name)}</h3><p><span class="rarity-dot"></span>${escapeHtml(c.rarity)} • ${escapeHtml(c.type)} • ${escapeHtml(c.set)}</p></article>`).join(''):'<div class="effect-item"><div><strong>No saved cards found</strong><small>Save a card to build your local design library.</small></div></div>'}
function reset(){Object.entries(defaults).forEach(([k,v])=>{if(k==='exhaust'||k==='upgradeable')$(k).checked=v;else $(k).value=v});artData='';effects=[{action:'damage',amount:18,status:'',condition:'target-below-40'}];currentSavedId='';$('artFrame').style.backgroundImage='';$('artFrame').querySelector('.art-placeholder').style.display='grid';renderEffects()}
fields.forEach(id=>$(id).addEventListener('input',()=>{currentSavedId='';render()}));
document.querySelectorAll('.section-link').forEach(b=>b.addEventListener('click',()=>showSection(b.dataset.section)));
$('artInput').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{artData=r.result;$('artFrame').style.backgroundImage=`url(${artData})`;$('artFrame').querySelector('.art-placeholder').style.display='none';currentSavedId='';render()};r.readAsDataURL(f)});
$('addEffect').addEventListener('click',()=>{effects.push({action:$('effectAction').value,amount:Number($('effectAmount').value),status:$('effectStatus').value.trim(),condition:$('effectCondition').value});renderEffects()});
$('effectList').addEventListener('click',e=>{const i=e.target.dataset.removeEffect;if(i!==undefined){effects.splice(Number(i),1);renderEffects()}});
$('saveCard').addEventListener('click',saveCard);$('newCard').addEventListener('click',reset);$('resetCard').addEventListener('click',reset);
$('librarySearch').addEventListener('input',renderLibrary);$('libraryRarity').addEventListener('change',renderLibrary);$('cardLibrary').addEventListener('click',e=>{const cardEl=e.target.closest('[data-card-id]');if(!cardEl)return;const card=library().find(c=>c.id===cardEl.dataset.cardId);if(card)loadCard(card)});
$('downloadJson').addEventListener('click',()=>{const d=data();const blob=new Blob([JSON.stringify(d,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(d.id||'game-card')+'.json';a.click();URL.revokeObjectURL(a.href)});
$('copyJson').addEventListener('click',async()=>{await navigator.clipboard.writeText(JSON.stringify(data(),null,2));$('copyJson').textContent='Copied';setTimeout(()=>$('copyJson').textContent='Copy JSON',1200)});
$('exportLibrary').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({schemaVersion:2,cards:library()},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='lady-delilah-card-library.json';a.click();URL.revokeObjectURL(a.href)});
$('clearLibrary').addEventListener('click',()=>{if(confirm('Clear every locally saved game card in this browser?')){setLibrary([]);renderLibrary()}});
renderEffects();renderLibrary();render();
